name: hello_world
description: A simple, single-file Shorebird application.
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  shorebird: ^0.0.1-dev.3

dev_dependencies:
  lints: ^2.0.0
