name: shorebird_flutter
description: Flutter serverless
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shorebird:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/shorebird

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Dependency overrides are ignored by packages who depend on us.
dependency_overrides:
  shorebird:
    path: ../shorebird
