name: updater_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  sembast: ^3.4.0+6
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3
  version: ^3.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
