name: publisher
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-266.0.dev <4.0.0'

# Add regular dependencies here.
dependencies: 
  args: ^2.4.0
  http: ^0.13.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
