import 'package:shorebird/annotations.dart';
import 'package:shorebird/shorebird.dart';

import 'src/gen/client.dart'; // Generated by `shorebird generate`.

@Endpoint()
Future<String> hello(RequestContext context) async {
  return 'Hello, world!';
}

void main() async {
  var client = Client();
  var result = await client.hello();
  print(result); // Prints 'Hello, world!'
}



