name: simple_rpc
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0
  shelf: ^1.4.0
  shorebird:
    path: ../../packages/shorebird

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
