name: simple_rpc
description: An example of using Shorebird.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  shorebird: ^0.0.1-dev.1
  # Remove once `shorebird generate` can generate toJson/fromJson itself.
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  # Remove once `shorebird generate` can generate toJson/fromJson itself.
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
# dependency_overrides:
#   shorebird:
#     path: ../../packages/shorebird/
