name: shorebird
description: Provides zero-configuration serverless Dart in the cloud.
version: 0.0.1-dev.3
repository: https://github.com/shorebirdtech/shorebird/tree/main/packages/shorebird

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.4
  mongo_dart: ^0.8.1
  sembast: ^3.3.1
  # To be removed once `shorebird generate` is smart enough:
  json_annotation: ^4.7.0
  # To be removed, Shorebird CLI:
  analyzer: ^5.2.0
  path: ^1.8.2
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  source_gen: ^1.2.6
  process: ^4.2.4
  args: ^2.3.1
  archive: ^3.3.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
