name: shorebird
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  eventsource:
    git: https://github.com/eseidel/dart-eventsource.git
  shelf: ^1.4.0
  shelf_eventsource:
    git: https://github.com/eseidel/dart-shelf_eventsource.git
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  eventsource:
    git: https://github.com/eseidel/dart-eventsource.git
