name: shorebird
description: Dart serverless
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.4
  mongo_dart: ^0.8.1
  json_annotation: ^4.7.0
  args: ^2.3.1
  sembast: ^3.3.1
  analyzer: ^5.2.0
  path: ^1.8.2
  code_builder: ^4.3.0
  dart_style: ^2.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
